project:
  title: "Milano Air Quality Dashboard"
  type: website
  output-dir: docs
  # pre-render: npm install; node js/translate-palettes.js
  render:
    - index.qmd
  resources:
    - js/
    - data/tokyo-palette.json
  preview:
    port: 4200
    
format:
  html:
    echo: false
    theme: default
    css: style/style.css
    page-layout: custom 
    margin-left: 20px
    margin-top: 10px 
    margin-right: 30px
    margin-bottom: 10px
    fontsize: 16px

execute:
  freeze: auto



